# Generated by Django 5.0.7 on 2024-09-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_gerenciarproduto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerenciarcategoria',
            options={'verbose_name_plural': 'GerenciarCategoria'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarcomentario',
            options={'verbose_name_plural': 'GerenciarComentario'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarpagina_home',
            options={'verbose_name_plural': 'GerenciarPagina_Home'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarpagina_inicial',
            options={'verbose_name_plural': 'GerenciarPagina_Inicial'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarproduto',
            options={'verbose_name_plural': 'GerenciarProduto'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarreceita',
            options={'verbose_name_plural': 'GerenciarReceita'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarusuario',
            options={'verbose_name_plural': 'GerenciarUsuario'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarvivencia',
            options={'verbose_name_plural': 'GerenciarVivencia'},
        ),
        migrations.RenameField(
            model_name='gerenciarpagina_inicial',
            old_name='descricao',
            new_name='detalhamento',
        ),
        migrations.RemoveField(
            model_name='gerenciarpagina_inicial',
            name='titulo',
        ),
        migrations.AddField(
            model_name='gerenciarpagina_inicial',
            name='sistomas',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerenciarpagina_inicial',
            name='tratamentos',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
