# Generated by Django 5.0.7 on 2024-10-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_sistomas_gerenciarpagina_inicial_sintomas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GerenciarPagina_Inicial',
            new_name='GerenciarIndex',
        ),
        migrations.AlterModelOptions(
            name='gerenciarindex',
            options={'verbose_name_plural': 'GerenciarIndex'},
        ),
    ]
