# Generated by Django 5.0.7 on 2024-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_gerenciarpagina_inicial_gerenciarindex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciarPagina_Inicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhamento', models.CharField(max_length=1000)),
                ('sintomas', models.CharField(max_length=1000)),
                ('tratamentos', models.CharField(max_length=1000)),
                ('nome_alergia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'GerenciarPagina_Inicial',
            },
        ),
        migrations.DeleteModel(
            name='GerenciarIndex',
        ),
        migrations.DeleteModel(
            name='GerenciarPagina_Home',
        ),
    ]
