# Generated by Django 5.1.2 on 2024-10-22 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_gerenciarpagina_inicial_delete_gerenciarindex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerenciarusuario',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='gerenciarusuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='gerenciarcomentario',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerenciarcomentario',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerenciarcomentario',
            name='nome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.gerenciarusuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gerenciarcomentario',
            name='mensagem',
            field=models.TextField(),
        ),
    ]
