# Generated by Django 5.1.2 on 2024-10-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_gerenciarusuario_senha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gerenciarcomentario',
            old_name='nome',
            new_name='usuario',
        ),
    ]
