# Generated by Django 5.1.2 on 2024-10-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_nome_gerenciarcomentario_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerenciarproduto',
            options={},
        ),
        migrations.AlterField(
            model_name='gerenciarproduto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
