# Generated by Django 5.1.2 on 2024-10-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_gerenciarproduto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerenciarcategoria',
            options={},
        ),
        migrations.AlterField(
            model_name='gerenciarproduto',
            name='descricao',
            field=models.TextField(),
        ),
    ]
