# Generated by Django 5.1.2 on 2024-10-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_gerenciarcategoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerenciarcategoria',
            options={'verbose_name_plural': 'GerenciarCategoria'},
        ),
        migrations.AlterField(
            model_name='gerenciarproduto',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
