# Generated by Django 5.1.2 on 2024-10-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_gerenciarcategoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciarreceita',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gerenciarproduto',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='GerenciarCategoria',
        ),
    ]
