# Generated by Django 5.1.2 on 2024-10-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_gerenciarpagina_inicial_sintomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='sintomas',
            field=models.CharField(max_length=1000),
        ),
    ]
