# Generated by Django 5.1.2 on 2024-10-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_gerenciarpagina_inicial_sintomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='detalhamento',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='sintomas',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='tratamentos',
            field=models.TextField(max_length=1000),
        ),
    ]
