# Generated by Django 5.1.2 on 2024-10-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_gerenciarreceita_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='detalhamento',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='sintomas',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='tratamentos',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarreceita',
            name='ingredientes',
            field=models.JSONField(),
        ),
    ]
