# Generated by Django 5.1.2 on 2024-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_gerenciarpagina_inicial_detalhamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerenciarreceita',
            options={'verbose_name_plural': 'GerenciarReceita'},
        ),
        migrations.RemoveField(
            model_name='gerenciarreceita',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='gerenciarreceita',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='gerenciarreceita',
            name='categoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerenciarreceita',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gerenciarreceita',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gerenciarreceita',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
