# Generated by Django 5.1.2 on 2024-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_gerenciarreceita_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerenciarreceita',
            options={},
        ),
        migrations.RemoveField(
            model_name='gerenciarreceita',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='gerenciarreceita',
            name='img',
        ),
        migrations.AddField(
            model_name='gerenciarreceita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/'),
        ),
        migrations.AddField(
            model_name='gerenciarreceita',
            name='ingredientes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='detalhamento',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='sintomas',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='tratamentos',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarreceita',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gerenciarreceita',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gerenciarusuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
