# Generated by Django 5.1.2 on 2024-10-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_gerenciarreceita_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciarcomentario',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_email', to='app.gerenciarusuario'),
        ),
        migrations.AlterField(
            model_name='gerenciarcomentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_usuario', to='app.gerenciarusuario'),
        ),
        migrations.AlterField(
            model_name='gerenciarusuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
