# Generated by Django 5.1.2 on 2024-10-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_gerenciarcomentario_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerenciarcomentario',
            options={'verbose_name_plural': 'GerenciarComentários'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarpagina_inicial',
            options={'verbose_name_plural': 'GerenciarPáginas Iniciais'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarusuario',
            options={'verbose_name_plural': 'GerenciarUsuários'},
        ),
        migrations.AlterModelOptions(
            name='gerenciarvivencia',
            options={'verbose_name_plural': 'GerenciarVivências'},
        ),
        migrations.AddField(
            model_name='gerenciarcomentario',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gerenciarcomentario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='gerenciarproduto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gerenciarvivencia',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gerenciarvivencia',
            name='img',
            field=models.ImageField(upload_to='vivencias/'),
        ),
    ]
