# Generated by Django 5.1.2 on 2024-10-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_gerenciarcomentario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerenciarreceita',
            options={'verbose_name_plural': 'GerenciarReceita'},
        ),
        migrations.RemoveField(
            model_name='gerenciarreceita',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='gerenciarreceita',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='gerenciarreceita',
            name='categoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerenciarreceita',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gerenciarcomentario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='gerenciarcomentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gerenciarusuario'),
        ),
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='detalhamento',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='sintomas',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarpagina_inicial',
            name='tratamentos',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gerenciarreceita',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gerenciarreceita',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gerenciarusuario',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
